name: Deploy on Serve
run-name: ${{ github.actor }} lance le deploiement
on:
       push:
              branches:
                     - master

env:
       NODE_VERSION: "16"
       NAME_ARTIFICAT: "story-helper"
       REMOTE_TARGET: /home/debianftp/www/api-story-helper
       PATH_API: ./api-story-idea
       PATH_APP: ./story-helper

jobs:
       build:
              runs-on: ubuntu-latest
              defaults:
                     run:
                            working-directory: ${{ env.PATH_API }}
              steps:
                     - uses: actions/checkout@master

                     - name: Check node
                       uses: actions/setup-node@master
                       with:
                              node-version: ${{ env.NODE_VERSION }}
                              cache: "npm"
                              cache-dependency-path: ${{ env.PATH_API }}/package-lock.json

                     - run: npm install

                     - name: Build
                       run: node ace build
                       working-directory: ${{ env.PATH_API }}

                     - name: get env
                       run: cp .env.production ./build/.env

                     - name: Artifact
                       uses: actions/upload-artifact@v1
                       with:
                              name: ${{ env.NAME_ARTIFICAT }}
                              path: ${{ env.PATH_API }}/build

       SSH:
              runs-on: ubuntu-latest
              steps:
                     - uses: actions/checkout@master

                     - name: Get artifact
                       uses: actions/download-artifact@v1
                       with:
                              name: ${{ env.NAME_ARTIFICAT }}
                              path: ./build
