name: Deploy on Serve
run-name: ${{ github.actor }} lance le deploiement
on:
       push:
              branches:
                     - master

env:
       NODE_VERSION: "16"
       NAME_ARTIFICAT: "story-helper"
       REMOTE_TARGET: /home/debianftp/www/api-story-helper

jobs:
       build:
              runs-on: ubuntu-latest
              steps:
                     - uses: actions/checkout@master

                     - name: create artifact
                       uses: actions/upload-artifact@v1
                       with:
                              name: ${{ env.NAME_ARTIFICAT }}
                              path: /

       deploy:
              runs-on: ubuntu-latest
              needs: build
              steps:
                     - name: checkout node
                       uses: actions/checkout@master

                     - name: checkout 2
                       uses: actions/setup-node@master
                       with:
                              node-version: ${{ env.NODE_VERSION }}

                     - name: Get artifact
                       uses: actions/download-artifact@v1
                       with:
                              name: ${{ env.NAME_ARTIFICAT }}
                              path: ./
