name: Deploy React
run-name: ${{ github.actor }} lance le deploiement de REACT
on:
       push:
              branches:
                     - master

env:
       NODE_VERSION: "16.17.1"
       NAME_ARTIFACT_REACT: "story-helper-react"
       PATH_REACT: ./story-helper
       PATH_APP: ./story-helper

jobs:
       BUILDREACT:
              runs-on: ubuntu-latest
              defaults:
                     run:
                            working-directory: ${{ env.PATH_REACT }}
              steps:
                     - uses: actions/checkout@master

                     - uses: actions/setup-node@master
                       with:
                              node-version: ${{ env.NODE_VERSION }}
                              cache: "npm"
                              cache-dependency-path: ${{ env.PATH_REACT }}/package-lock.json

                     - run: npm install

                     - run: CI= npm run build

                     - name: artificat react
                       uses: actions/upload-artifact@v1
                       with:
                              name: ${{ env.NAME_ARTIFACT_REACT }}
                              path: ${{ env.PATH_REACT }}/build

       DEPLOYREACT:
              runs-on: ubutun-latest
              needs: BUILDREACT
              defaults:
                     run:
                            working-directory: ${{ env.PATH_REACT }}
              steps:
                     - uses: actions/checkout@master

                     - uses: actions/setup-node@master
                       with:
                              node-version: ${{ env.NODE_VERSION }}
                              cache: "npm"
                              cache-dependency-path: ${{ env.PATH_REACT }}/package-lock.json

                     - name: download artifact
                       uses: actions/download-artifact@v1
                       with:
                              name: ${{ env.NAME_ARTIFACT_REACT }}
                              path: ./

                     - name: FTP
                       uses: SamKirkland/FTP-Deploy-Action@4.3.2
                       with:
                              server: ftp.cluster023.hosting.ovh.net
                              username: ${{ secrets.FTP_USER }}
                              password: ${{ secrets.FTP_PASSWORD }}
                              server-dir: ./api-story-helper/
